config/routes.rb
Hostadmin::Application.routes.draw do

	resources :domains do
		resources :mailusers
		
		resources :mailalias_sources
	end
	
	resources :mailalias_sources
	
	resources :mailusers
	
	resources :users do

	end

  resources :voip_accounts do
    member do 
      get 'cdr'
      post 'cdr_data'
    end
  end

  resources :voip_costs do
    member do 
      get 'duplicate'
    end
  end

	match '/login' => "index#login"
	match '/logout' => "index#logout"
  match '/change_email_password' => "index#change_email_password"
	root :to => "index#index"
	

end

app/models/voip_cost.rb
class VoipCost < ActiveRecord::Base
	def for_duration(seconds)
		(flagfall.to_f + timecost * (seconds.to_f / timeperiod.to_f)).ceil
	end

	def self.matching(number)
		where(["? LIKE number", number]).order("CHAR_LENGTH(number) desc")
	end
	
	def self.from_date(date)
		where(["start_date < ?", date]).order("start_date desc")
	end

end

app/controllers/voip_costs_controller.rb
class VoipCostsController < ApplicationController
  before_filter :logged_in
  before_filter :logged_in_administrator, :except => ["show"]
  # GET /voip_costs
  # GET /voip_costs.json
  def index
    @voip_costs = VoipCost.order("start_date desc").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @voip_costs }
    end
  end

  # GET /voip_costs/1
  # GET /voip_costs/1.json
  def show
    @voip_cost = VoipCost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @voip_cost }
    end
  end

  # GET /voip_costs/new
  # GET /voip_costs/new.json
  def new
    @voip_cost = VoipCost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @voip_cost }
    end
  end

  def duplicate
    voip_cost = VoipCost.find(params[:id])
    @voip_cost = voip_cost.dup
    @voip_cost.start_date = Date.today
    render :action => "new"
  end

  # GET /voip_costs/1/edit
  def edit
    @voip_cost = VoipCost.find(params[:id])
  end

  # POST /voip_costs
  # POST /voip_costs.json
  def create
    @voip_cost = VoipCost.new(params[:voip_cost])

    respond_to do |format|
      if @voip_cost.save
        format.html { redirect_to @voip_cost, notice: 'Voip cost was successfully created.' }
        format.json { render json: @voip_cost, status: :created, location: @voip_cost }
      else
        format.html { render action: "new" }
        format.json { render json: @voip_cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /voip_costs/1
  # PUT /voip_costs/1.json
  def update
    @voip_cost = VoipCost.find(params[:id])

    respond_to do |format|
      if @voip_cost.update_attributes(params[:voip_cost])
        format.html { redirect_to @voip_cost, notice: 'Voip cost was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @voip_cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voip_costs/1
  # DELETE /voip_costs/1.json
  def destroy
    @voip_cost = VoipCost.find(params[:id])
    @voip_cost.destroy

    respond_to do |format|
      format.html { redirect_to voip_costs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/voip_costs_helper.rb
module VoipCostsHelper
end

app/views/voip_costs/_form.html.erb
<%= form_for(@voip_cost) do |f| %>
  <% if @voip_cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voip_cost.errors.count, "error") %> prohibited this voip_cost from being saved:</h2>

      <ul>
      <% @voip_cost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :flagfall %><br />
    <%= f.number_field :flagfall %>
  </div>
  <div class="field">
    <%= f.label :timecost %><br />
    <%= f.text_field :timecost %>
  </div>
  <div class="field">
    <%= f.label :timeperiod %><br />
    <%= f.number_field :timeperiod %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/voip_costs/edit.html.erb
<h1>Editing voip_cost</h1>

<%= render 'form' %>

<%= link_to 'Show', @voip_cost %> |
<%= link_to 'Back', voip_costs_path %>

app/views/voip_costs/index.html.erb
<h1>Listing voip_costs</h1>

<table width="100%">
  <tr>
    <th>Description</th>
    <th></th>
    <th>Cost</th>
    <th></th>
  </tr>

<% @voip_costs.each do |voip_cost| %>
  <tr>
    <td><%= link_to voip_cost.name, voip_cost %></td><td><%= voip_cost.start_date.strftime("%y-%m-%d") %></td>
    <td><%= voip_cost.flagfall %><% if voip_cost.timecost > 0 %> + <%= voip_cost.timecost %> per <%= voip_cost.timeperiod %>s <% end %></td>
    <td><%= link_to 'D', voip_cost, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Voip cost', new_voip_cost_path %>

app/views/voip_costs/new.html.erb
<h1>New voip_cost</h1>

<%= render 'form' %>

<%= link_to 'Back', voip_costs_path %>

app/views/voip_costs/show.html.erb
<% content_for :title do %>VoIP Cost Details for <%= @voip_cost.name %><% end -%>
<h1>VoIP Cost Details for <%= @voip_cost.name %></h1>
Applicable From: <%= @voip_cost.start_date.strftime("%y-%m-%d") %>
<p id="notice"><%= notice %></p>

<p>
	<b>Numbers Matching:</b>
	<%= @voip_cost.number %>
</p>

<p>
	<b>Cost:</b>
	<%= @voip_cost.flagfall %> cents plus <%= @voip_cost.timecost %> cents every <%= @voip_cost.timeperiod %> seconds 
</p>

Examples:
<blockquote>
10 seconds would cost <%= number_to_currency(@voip_cost.for_duration(10) / 100.0) %><br/>
1 Minute would cost <%= number_to_currency(@voip_cost.for_duration(60) / 100.0) %><br/>
5 Minutes would cost <%= number_to_currency(@voip_cost.for_duration(300) / 100.0) %><br/>
10 Minutes would cost <%= number_to_currency(@voip_cost.for_duration(600) / 100.0) %><br/>
<%= text_field_tag(:cost_time, "", :size => 5) %>seconds would cost $<%= text_field_tag(:cost_cost, "", :size => 5)%><br/>
</blockquote>

<script>
var flagfall = <%= @voip_cost.flagfall %>;
var cost = <%= @voip_cost.timecost %>;
var time = <%= @voip_cost.timeperiod %>;

function calc_cost() {
	var calctime = parseInt($("#cost_time").val());
	if (isNaN(calctime)) {
		$("#cost_cost").val("Unknown");	
		return;
	}
	var calccost = flagfall;
	if (cost > 0)
		calccost += (cost * calctime) / time;
	calccost = Math.ceil(calccost) / 100.0;

	$("#cost_cost").val(calccost);
}

$().ready(function() {
	$("#cost_time").bind('keyup', calc_cost);
});
</script>

<%= link_to 'Duplicate', duplicate_voip_cost_path(@voip_cost) %> |
<%= link_to 'Edit', edit_voip_cost_path(@voip_cost) %> |
<%= link_to 'Back', voip_costs_path %>