config/routes.rb
Hostadmin::Application.routes.draw do

	resources :domains do
		resources :mailusers
		
		resources :mailalias_sources
	end
	
	resources :mailalias_sources
	
	resources :mailusers
	
	resources :users do

	end

  resources :voip_accounts do
    member do 
      get 'cdr'
      post 'cdr_data'
    end
  end

  resources :voip_costs do
    member do 
      get 'duplicate'
    end
  end

	match '/login' => "index#login"
	match '/logout' => "index#logout"
  match '/change_email_password' => "index#change_email_password"
	root :to => "index#index"
	

end

app/models/domain.rb
class Domain < ActiveRecord::Base
	belongs_to :owner, :class_name => "User"
	has_many :aliases, :class_name => "MailaliasSource"
	has_many :users, :class_name => "Mailuser"
	has_many :mailalias_source, :class_name => "MailaliasSource"
	has_many :mailuser, :class_name => "Mailuser"
	
	def expired
		return DateTime.now >= paiduntil
	end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
	before_filter :logged_in
	
  # GET /domains
  # GET /domains.xml
  def index
		if @currentuser.administrator
    	@domains = Domain.find(:all)
		else
			@domains = Domain.find_all_by_owner_id(@currentuser.id)
		end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @domains }
    end
		if false
			redirect_to :controller => 'index', :action => 'login'			
		end

  end

  # GET /domains/1
  # GET /domains/1.xml
  def show
    @domain = Domain.find(params[:id])
		if !@currentuser.administrator and @domain.owner != @currentuser
	    respond_to do |format|
	      format.html { redirect_to :action => "index" }
	    end
			return
		end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @domain }
    end
  end

  # GET /domains/new
  # GET /domains/new.xml
  def new
    @domain = Domain.new
		if !@currentuser.administrator
			redirect_to :action => "index"
			return
		end
		
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @domain }
    end
  end

  # GET /domains/1/edit
  def edit
    @domain = Domain.find(params[:id])
		if !@currentuser.administrator
			redirect_to :action => "index"
			return
		end
  end

  # POST /domains
  # POST /domains.xml
  def create
    @domain = Domain.new(params[:domain])
		if !@currentuser.administrator
			redirect_to :action => "index"
			return
		end
		
    respond_to do |format|
      if @domain.save
        flash[:notice] = 'Domain was successfully created.'
        format.html { redirect_to(@domain) }
        format.xml  { render :xml => @domain, :status => :created, :location => @domain }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @domain.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /domains/1
  # PUT /domains/1.xml
  def update
    @domain = Domain.find(params[:id])
		if !@currentuser.administrator
			redirect_to :action => "index"
			return
		end
    respond_to do |format|
      if @domain.update_attributes(params[:domain])
        flash[:notice] = 'Domain was successfully updated.'
        format.html { redirect_to(@domain) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @domain.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.xml
  def destroy
    @domain = Domain.find(params[:id])
		if !@currentuser.administrator
			redirect_to :action => "index"
			return
		end

		@domain.destroy
    respond_to do |format|
      format.html { redirect_to(domains_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/edit.html.erb
<% content_for :title do %>Editing Domain<% end -%>
Editing Domain
<%= form_for(@domain) do |f| %>
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %></div>
<% end %>
<%= errors_for(@domain, "Opps, unable to edit domain").html_safe %>
<div class="field_container"><%= f.label :name %><%= f.text_field :name %></div>
<div class="field_container"><%= f.label :paiduntil %><%= f.date_select :paiduntil %></div>
<div class="field_container"><%= f.label :owner %><%= f.select(:owner_id, User.find(:all).collect {|c| [ c.name, c.id ] }) %></div>
<div class="field_container"><%= f.label :email %><%= f.check_box :email %></div>
<%= f.submit "Update" %>
<% end %>
<br/>
<br/>
<br/>
<br/>
<br/>

app/views/domains/index.html.erb
<% content_for :title do %>Domain Details<% end -%>
<h1>Domain Details</h1>
<table width="100%">
  <tr>
    <th>Name</th>
    <th>Paid up until</th>
<% if @currentuser.administrator -%>
    <th>Owner</th>
<% end -%>
  </tr>

<% for domain in @domains %>
  <tr>
    <td <% if domain.expired%>class="red"<%end%>><%= link_to(domain.name, domain) %></td>
    <td <% if domain.expired%>class="red"<%end%>><%= domain.paiduntil %></td>
<% if @currentuser.administrator -%>
    <td <% if domain.expired%>class="red"<%end%>><%= domain.owner.name %></td>
    <td><%= link_to 'E', edit_domain_path(domain) %> <%= link_to 'D', domain, :confirm => 'Are you sure?', :method => :delete %></td>
<% end -%>
  </tr>
<% end %>
</table>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

app/views/domains/new.html.erb
<% content_for :title do %>New Domain<% end -%>
<h1>New Domain</h1>
<%= form_for(@domain) do |f| %>
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %></div>
<% end %>
<%= errors_for(@domain, "Opps, unable to edit domain").html_safe %>
<div class="field_container"><%= f.label :name %><%= f.text_field :name %></div>
<div class="field_container"><%= f.label :paiduntil %><%= f.date_select :paiduntil %></div>
<div class="field_container"><%= f.label :owner %><%= f.select(:owner_id, User.find(:all).collect {|c| [ c.name, c.id ] }) %></div>
<div class="field_container"><%= f.label :email %><%= f.check_box :email %></div>
<%= f.submit "Update" %>
<% end %>
<br/>
<br/>
<br/>
<br/>
<br/>

app/views/domains/show.html.erb
<% content_for :title do %>Domain Details<% end -%>
<h1>Domain Details</h1>
<% if @currentuser.administrator -%>
<%= link_to("Edit", edit_domain_path(@domain)) %> | <%= link_to 'Delete', @domain, :confirm => 'Are you sure?', :method => :delete %>
<% end -%>
<p>
  <b>Name:</b>
  <%=h @domain.name %>
</p>

<p>
  <b>Paiduntil:</b>
  <%=h @domain.paiduntil %>
</p>

<p>
  <b>Owner:</b>
  <%=h @domain.owner.name %>
</p>
<% if @domain.email %>
<h1>Email Admin for <%= @domain.name %></h1>
<h2>Aliases</h2>
<table width="100%">
  <tr>
    <th>Source</th>
    <th>Destinations</th>
  </tr>
<% for source in @domain.aliases %>
	<tr>
		<td><%= link_to("#{source.source}@#{@domain.name}", source) %></td>
		<% index = 1 %>
		<td><% for destination in source.destinations -%>
			<%= destination.destination -%><% if index < source.destinations.size %>, <% end -%>
			<% index +=1 -%>
			<% end %></td>
	  <td><%= link_to 'E', edit_mailalias_source_path(source) %> | <%= link_to 'D', source, :confirm => 'Are you sure?', :method => :delete %></td>	
	</tr>
<% end %>
</table>
<h2>Users</h2>
<table width="100%">
	<tr>
    <th>Login/Email</th>
    <th>Quota</th>
  </tr>
<% for mailuser in @domain.users %>
<tr>
	<td><%= link_to(mailuser.name + "@" + @domain.name, mailuser) %></td>
	<td><%=h number_with_delimiter(mailuser.quota) %> MB</td>
  <td><%= link_to 'E', edit_mailuser_path(mailuser) %> | <%= link_to 'D', mailuser, :confirm => 'Are you sure?', :method => :delete %></td>
</tr>
<% end %>
</table>
<% end %>