config/routes.rb
Hostadmin::Application.routes.draw do

	resources :domains do
		resources :mailusers
		
		resources :mailalias_sources
	end
	
	resources :mailalias_sources
	
	resources :mailusers
	
	resources :users do

	end

  resources :voip_accounts do
    member do 
      get 'cdr'
      post 'cdr_data'
    end
  end

  resources :voip_costs do
    member do 
      get 'duplicate'
    end
  end

	match '/login' => "index#login"
	match '/logout' => "index#logout"
  match '/change_email_password' => "index#change_email_password"
	root :to => "index#index"
	

end

app/models/voip_account.rb
class VoipAccount < ActiveRecord::Base
	belongs_to :owner, :class_name => "User"

	def cdr_data(hash)
		start_date = hash[:from]
		end_date = hash[:to]

		if ENV["RAILS_ENV"] == "development"
			table_name = "asterisk.cdr"
		else
			table_name = "asterisk_cdr.cdr"
		end
		
		sql = "SELECT billsec, calldate, dstphone, amaflags, disposition FROM #{table_name} WHERE calldate > '#{start_date} 00:01' AND calldate < '#{end_date} 23:59' AND accountcode = '#{name}' ORDER BY calldate"
		
		data = Array.new

		total = 0
		print("SQL: #{sql}")
		connection.execute(sql).each do |row|
			if row[3].to_i == 2 and row[4] == 'ANSWERED'
				cost = VoipCost.from_date(row[1]).matching(row[2]).first
				if cost != nil
					price = cost.for_duration(row[0].to_i)
					total += price
					data << {:duration => row[0], :date => row[1].to_i, :number => row[2], :price => price, :cost => cost.name, :cost_id => cost.id}
				else
					data << {:duration => row[0], :date => row[1].to_i, :number => row[2], :price => "UNKNOWN"}
				end
			end
		end
		
		{:total => total, :data => data}
	end
end

app/controllers/voip_accounts_controller.rb
class VoipAccountsController < ApplicationController
	before_filter :logged_in
	
	# GET /voip_accounts
	# GET /voip_accounts.json
	def index
		if @currentuser.administrator
			@voip_accounts = VoipAccount.all
		else
			@voip_accounts = VoipAccount.where(:owner_id => @currentuser.id)
		end

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @voip_accounts }
		end
	end

	# GET /voip_accounts/1
	# GET /voip_accounts/1.json
	def show
		@voip_account = VoipAccount.find(params[:id])
		if !@currentuser.administrator and @voip_account.owner != @currentuser
			redirect_to :action => "index"
			return
		end

		respond_to do |format|
			format.html # show.html.erb
			format.json { render json: @voip_account }
		end
	end

	def cdr
		@voip_account = VoipAccount.find(params[:id])
		if !@currentuser.administrator and @voip_account.owner != @currentuser
			redirect_to :action => "index"
			return
		end

		@date2 = Date.today
		@date1 = @date2.at_beginning_of_month 


		respond_to do |format|
			format.html # show.html.erb
			#format.json { render json: @voip_account }
		end
	end

	def cdr_data
		@voip_account = VoipAccount.find(params[:id])
		if !@currentuser.administrator and @voip_account.owner != @currentuser
			redirect_to :action => "index"
			return
		end

		date1 = Date.civil(params[:date1][:year].to_i, params[:date1][:month].to_i, params[:date1][:day].to_i)
		date2 = Date.civil(params[:date2][:year].to_i, params[:date2][:month].to_i, params[:date2][:day].to_i)

		@cdrs = @voip_account.cdr_data({:from => date1, :to => date2})

		respond_to do |format|
			format.json { 
				render json: {
					from: date1, to: date2, voip_account_id: @voip_account.id,
					cdrs: @cdrs[:data], total: @cdrs[:total]
				}
			}
			format.csv {
				require 'csv'
			}
		end
	end

	# GET /voip_accounts/new
	# GET /voip_accounts/new.json
	def new
		if !@currentuser.administrator
			redirect_to :action => "index"
			return
		end
		@voip_account = VoipAccount.new

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @voip_account }
		end
	end

	# GET /voip_accounts/1/edit
	def edit
		@voip_account = VoipAccount.find(params[:id])
		if !@currentuser.administrator and @voip_account.owner != @currentuser
			redirect_to :action => "index"
			return
		end
	end

	# POST /voip_accounts
	# POST /voip_accounts.json
	def create
		if !@currentuser.administrator
			redirect_to :action => "index"
			return
		end		
		@voip_account = VoipAccount.new(params[:voip_account])

		respond_to do |format|
			if @voip_account.save
				format.html { redirect_to @voip_account, notice: 'Voip account was successfully created.' }
				format.json { render json: @voip_account, status: :created, location: @voip_account }
			else
				format.html { render action: "new" }
				format.json { render json: @voip_account.errors, status: :unprocessable_entity }
			end
		end
	end

	# PUT /voip_accounts/1
	# PUT /voip_accounts/1.json
	def update
		@voip_account = VoipAccount.find(params[:id])
		if !@currentuser.administrator and @voip_account.owner != @currentuser
			redirect_to :action => "index"
			return
		end

		respond_to do |format|
			if @voip_account.update_attributes(params[:voip_account])
				format.html { redirect_to @voip_account, notice: 'Voip account was successfully updated.' }
				format.json { head :ok }
			else
				format.html { render action: "edit" }
				format.json { render json: @voip_account.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /voip_accounts/1
	# DELETE /voip_accounts/1.json
	def destroy
		@voip_account = VoipAccount.find(params[:id])
		if !@currentuser.administrator and @voip_account.owner != @currentuser
			redirect_to :action => "index"
			return
		end

		@voip_account.destroy

		respond_to do |format|
			format.html { redirect_to voip_accounts_url }
			format.json { head :ok }
		end
	end
end

app/helpers/voip_accounts_helper.rb
module VoipAccountsHelper
end

app/views/voip_accounts/_csv_button.html.erb
<%= button_to(cdr_data_voip_account_path(account,	:date1 => {:year => date1.year, :month => date1.month, :day => date1.day},
												 	:date2 => {:year => date2.year, :month => date2.month, :day => date2.day}, :format => :csv)

app/views/voip_accounts/_form.html.erb
<%= form_for(@voip_account) do |f| %>
  <% if @voip_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voip_account.errors.count, "error") %> prohibited this voip_account from being saved:</h2>

      <ul>
      <% @voip_account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field_container"><%= f.label :name %>
<% if @currentuser.administrator -%>
<%= f.text_field :name %>
<%- else %>
<%= @voip_account.name %>
<%- end %></div>
<div class="field_container"><%= f.label :password %><%= f.text_field :password %></div>
<div class="field_container"><%= f.label :channels %>
<% if @currentuser.administrator -%>
<%= f.number_field :channels %>
<%- else %>
<%= @voip_account.channels %>
<%- end %></div></div>

<% if @currentuser.administrator -%>
<div class="field_container"><%= f.label :owner %><%= f.select(:owner_id, User.find(:all).collect {|c| [ c.name, c.id ] }) %></div>  
<%- end %>
<%= f.submit "Update" %>
<% end %>
<br/>
<br/>
<br/>
<br/>
<br/>

app/views/voip_accounts/cdr.html.erb
<% content_for :title do %>Call Records<% end -%>
<h1>Call Records</h1>

<%= form_tag(cdr_data_voip_account_path(@voip_account), {:remote => true, :id => "search_cdrs", "data-type" => "json"}) do |f| %>
<div class="field_container"><%= label_tag :date1, "From" %><%= select_date @date1, :prefix => :date1 %> 00:00:01</div>
<div class="field_container"><%= label_tag :date2, "To" %><%= select_date @date2, :prefix => :date2 %> 23:59:59</div>
<%= submit_tag "Show", :disable_with => "Processing..." %>
<% end %>

<div id="cdr_display" class="hidden">
<span id="cdr_text"></span>
<table width="100%">
</table>
Total: $<span id="cdr_total"></span><br/>
</div>

<%= form_tag(cdr_data_voip_account_path(@voip_account, :format => :csv), :id => "cdr_csv_form", :class => "hidden") do |f| %>
<%= hidden_field(:date1, :year) %><%= hidden_field(:date1, :month) %><%= hidden_field(:date1, :day) %>
<%= hidden_field(:date2, :year) %><%= hidden_field(:date2, :month) %><%= hidden_field(:date2, :day) %>
<%= submit_tag "Above as CSV" %>
<% end %>

<script>
function CurrencyFormatted(amount) {
	var i = parseFloat(amount);
	if(isNaN(i)) { i = 0.00; }
	var minus = '';
	if(i < 0) { minus = '-'; }
	i = Math.abs(i);
	i = parseInt((i + .005) * 100);
	i = i / 100;
	s = new String(i);
	if(s.indexOf('.') < 0) { s += '.00'; }
	if(s.indexOf('.') == (s.length - 2)) { s += '0'; }
	s = minus + s;
	return s;
}

function PadNumber(value, digits) {
	var text = value + "";
	if (text.length < digits) {
		var padding = "";
		do
			padding += "0";
		while ((padding + text).length < digits)
		return padding + text;
	} else
		return text;
}

$("#search_cdrs").bind('ajax:success', function(evt, data, status, xhr) {
	var start_date = new Date(data.from);
	var end_date = new Date(data.to);
	var date = new Date();
	$("#cdr_text").html("Calls from " + start_date.toDateString() + " until " + end_date.toDateString());
	var index;
	var object;
	$("#cdr_display").removeClass("hidden");
	var table = $("#cdr_display").find("table");
	table.html("");
	table.html("<tr><th>Date/Time</th><th>Number</th><th>Number Type</th><th>Duration</th><th>Cost</th></tr>");
	var row;
	for(number in data.cdrs) {
		row = "<tr>";
		object = data.cdrs[number];
		date.setTime(object.date * 1000);
		dateString = date.getFullYear() + "-" + PadNumber((date.getMonth() + 1), 2) + "-" + PadNumber(date.getDate(),2);
		dateString += " " + PadNumber(date.getHours(),2) + ":" + PadNumber(date.getMinutes(),2) + ":" + PadNumber(date.getSeconds(),2);
		row += "<td>" + dateString + "</td>";
		row += "<td>" + object.number + "</td>";
		if (object.cost != "UNKNOWN")
			row += "<td><a href=\"/voip_costs/" + object.cost_id + "\">" + object.cost + "</a></td>";
		else
			row += "<td>UNKNOWN</td>";
		row += "<td>" + object.duration + "</td>";
		if (object.cost != "UNKNOWN")
			row += "<td>$" + CurrencyFormatted(object.price / 100.0) + "</td>";
		else
			row += "<td>UNKNOWN</td>";
		row += "</tr>";
		table.append(row);
	}
	$("#cdr_total").html("" + CurrencyFormatted(data.total / 100.0));
	var csv_form = $("#cdr_csv_form");
	csv_form.removeClass("hidden");
	csv_form.find("#date1_year").val(start_date.getFullYear());
	csv_form.find("#date1_month").val(start_date.getMonth() + 1);
	csv_form.find("#date1_dat").val(start_date.getDate());
	csv_form.find("#date2_year").val(end_date.getFullYear());
	csv_form.find("#date2_month").val(end_date.getMonth() + 1);
	csv_form.find("#date2_day").val(end_date.getDate());
});
</script>

app/views/voip_accounts/cdr_data.csv.erb
Date/Time,number,duration,type,cost
<%= CSV.generate do |csv|
  @cdrs[:data].each do |cdr|
    csv << [Time.at(cdr[:date]).rfc2822, cdr[:number], cdr[:duration], cdr[:cost], cdr[:price]]
  end
end.html_safe %>

app/views/voip_accounts/edit.html.erb
<h1>Editing voip_account</h1>

<%= render 'form' %>

<%= link_to 'Show', @voip_account %> |
<%= link_to 'Back', voip_accounts_path %>

app/views/voip_accounts/index.html.erb
<% content_for :title do %>Voip Accounts<% end -%>
<h1>Voip Accounts</h1>
<table width="100%">
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th></th>
    <% if @currentuser.administrator %><th></th><%- end %>
  </tr>

<% @voip_accounts.each do |voip_account| %>
  <tr>
    <td><%= link_to(voip_account.name, voip_account) %></td>
    <td><%= link_to(voip_account.password, edit_voip_account_path(voip_account)) %></td>
    <td><%= link_to 'Call Records', cdr_voip_account_path(voip_account) %></td>
    <% if @currentuser.administrator %><td><%= link_to 'Destroy', voip_account, confirm: 'Are you sure?', method: :delete %></td><%- end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Voip account', new_voip_account_path %>

app/views/voip_accounts/new.html.erb
<h1>New voip_account</h1>

<%= render 'form' %>

<%= link_to 'Back', voip_accounts_path %>

app/views/voip_accounts/show.html.erb
<% content_for :title do %>Voip Account Details<% end -%>
<h1>Voip Account Details</h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @voip_account.name %>
</p>

<p>
  <b>Password:</b>
  <%= @voip_account.password %>
</p>

<p>
  <b>Channels:</b>
  <%= @voip_account.channels %>
</p>

<%= link_to 'Call Records', cdr_voip_account_path(@voip_account) %> | 
<%= link_to 'Edit', edit_voip_account_path(@voip_account) %> |
<%= link_to 'Back', voip_accounts_path %>