config/routes.rb
Hostadmin::Application.routes.draw do

	resources :domains do
		resources :mailusers
		
		resources :mailalias_sources
	end
	
	resources :mailalias_sources
	
	resources :mailusers
	
	resources :users do

	end

  resources :voip_accounts do
    member do 
      get 'cdr'
      post 'cdr_data'
    end
  end

  resources :voip_costs do
    member do 
      get 'duplicate'
    end
  end

	match '/login' => "index#login"
	match '/logout' => "index#logout"
  match '/change_email_password' => "index#change_email_password"
	root :to => "index#index"
	

end

app/views/layouts/_sidebar.html.erb
<% if controller.action_name == "edit" and controller.controller_name == "users" -%>
<h2 class="selected">Modify Profile
<%- else %>
<h2><%= link_to("Modify Profile", edit_user_path(@currentuser)) -%>
<%- end %></h2>

<% if @currentuser.administrator %>
<% if controller.action_name == "index" and controller.controller_name == "users" -%>
<h2 class="selected">System Users
<%- else %>
<h2><%= link_to("System Users", users_path) -%>
<%- end %></h2>
<ul>
	<% if controller.action_name == "new" and controller.controller_name == "users" %>
		<li class="selected">Create New User
	<%- else %>
		<li><%= link_to("Create New User", new_user_path) -%>
	<%- end %></li>
</ul>
<%- end %>

<% if controller.controller_name != "domains" -%>
<h2><%= link_to("Domains", domains_path) %></h2>
<% else -%>
<h2>Domains</h2>
<ul>
<% if @currentuser.administrator -%>
	<%- if controller.action_name == "index" and controller.controller_name == "domains" %>
		<li class="selected">Show All Domains</span>
	<%- else %>
		<li><%= link_to("Show All Domains", domains_path) -%>
	<%- end %></li>
	<% if controller.action_name == "new" and controller.controller_name == "domains" %>
		<li class="selected">Create New Domain
	<%- else %>
		<li><%= link_to("Create New Domain", new_domain_path) -%>
	<%- end %></li>
<% else -%>
	<%- if controller.action_name == "index" and controller.controller_name == "domains" %>
		<li class="selected">Show My Domains</span>
	<%- else %>
		<li><%= link_to("Show My Domains", domains_path) -%>
	<%- end %></li>
<% end -%>
</ul>
<%- end %>
<br/>
<% if @domain -%>
	<% if controller.action_name == "show" and controller.controller_name == "domains" %>
		<h2 class="selected"><%= @domain.name %>
	<%- else %>
		<h2><%= link_to(@domain.name, @domain) %>
	<%- end %></h2>

	<% if @domain.email %>
	<h2>Email</h2>
	<ul>
		<%- if controller.action_name == "new" and controller.controller_name == "mailalias_sources" %>
			<li class="selected">Add Alias
		<%- else %>
			<li><%= link_to("Add Alias", new_domain_mailalias_source_path(@domain)) %>
		<%- end %></li>
		<%- if controller.action_name == "new" and controller.controller_name == "mailusers" %>
			<li class="selected">Add User
		<%- else %>
			<li><%= link_to("Add User", new_domain_mailuser_path(@domain)) %>
		<%- end %></li>
	</ul>
	<% end -%>
<% end -%>
<br/>

<%- if controller.controller_name != "voip_accounts" %>
<h2><%= link_to("VoIP Accounts", voip_accounts_path) %></h2>
<%- else %>
<h2>VoIP Accounts</h2>
<%- end %>
<ul>
<% if @currentuser.administrator -%>
<%- if controller.action_name == "index" and controller.controller_name == "voip_accounts" %>
		<li class="selected">Show All Accounts</span>
	<%- else %>
		<li><%= link_to("Show All Accounts", voip_accounts_path) -%>
	<%- end %></li>
	<% if controller.action_name == "new" and controller.controller_name == "voip_accounts" %>
		<li class="selected">Create New Account
	<%- else %>
		<li><%= link_to("Create New Accounts", new_voip_account_path) -%>
	<%- end %></li>
<% else -%>
	<%- if controller.action_name == "index" and controller.controller_name == "voip_accounts" %>
		<li class="selected">Show My Accounts</span>
	<%- else %>
		<li><%= link_to("Show My Accounts", voip_accounts_path) -%>
	<%- end %></li>
<% end -%>
</ul>

<%- if @currentuser.administrator -%>
<%- if controller.controller_name != "voip_costs" %>
<h2><%= link_to("VoIP Costings", voip_costs_path) %></h2>
<%- else %>
<h2>VoIP Costings</h2>
<%- end %>
<%- end %>

<h2><%= link_to("Logout", :action => "logout", :controller => "index") -%></h2>

app/views/layouts/base.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--

	Smooth and Sleek by christopher robinson
	http://www.edg3.co.uk/
	hope you enjoy it and find it usefull :)

-->
<html xmlns="http://www.w3.org/1999/xhtml">

<head profile="http://gmpg.org/xfn/11">
<title><%= yield(:title) %> | <%= SITE_NAME %> Admin</title>
<%= yield(:head) %>
<!--	<link rel="shortcut icon" href="image/favicon.ico" /> -->
	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="en-gb" />
	<meta http-equiv="imagetoolbar" content="false" />
	<meta name="author" content="Christopher Robinson" />
	<meta name="copyright" content="Copyright (c) Christopher Robinson 2005 - 2007" />
	<meta name="description" content="" />
	<meta name="keywords" content="" />	
	<meta name="last-modified" content="Sat, 01 Jan 2007 00:00:00 GMT" />
	<meta name="mssmarttagspreventparsing" content="true" />	
	<meta name="robots" content="index, follow, noarchive" />
	<meta name="revisit-after" content="7 days" />
</head>
<body>
	<div id="header">
		<div id="header_inside">
			<h1><span>Sektor</span> Seven</h1>
			<ul>
				<li><a href="about.html">About</a></li>
				<li><a href="https://support.sektorseven.net/">Support</a></li>
				<li><a class="active" href="#">Admin</a></li>
				<li><a href="products.html">Products</a></li>
				<li><a href="http://www.sektorseven.net/">News</a></li>
			</ul>
		</div>
	</div>

	<div id="content">
		<div id="content_inside">
			<div id="content_inside_sidebar">
			<% if content_for?(:sidebar) %><%= yield :sidebar %><% else %><%= render "layouts/sidebar" %><% end %>
			</div>
			<div id="content_inside_main">
<%= yield %>
			</div>	
		</div>	
	</div>

	<div id="footer">
		<div id="footer_inside">
			<p>Copyright &copy; <a href="#">Smooth and Sleek</a> 2007 | Designed by <a href="http://www.edg3.co.uk/">edg3.co.uk</a> | Sponsored by <a href="http://www.opendesigns.org/">Open Designs</a> | Valid <a href="http://jigsaw.w3.org/css-validator/">CSS</a> &amp; <a href="http://validator.w3.org/">XHTML</a></p>
		</div>
	</div>
</body>
</html>